[build]
  command = "yarn build"
  publish = ".next"

[functions]
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/**/*"]

[[redirects]]
  from = "/wam"
  to = "https://wamtogpa.lpdpunimelb.com/"
  status = 302
  force = true